CREATE TABLE IF NOT EXISTS EMPLOYEE (
EMPLOYEE_ID TEXT,
NAME TEXT,
CITY TEXT,
SALARY  REAL);

INSERT INTO EMPLOYEE (EMPLOYEE_ID,NAME ,CITY ,SALARY ) VALUES
('5001', 'James Hoog', 'New York', 10580),
('5002', 'Nail Knite', 'Paris', 16578),
('5005', 'Pit Alex', 'London', 11223),
('5006', 'Mc Lyon', 'Paris', 14819),
('5007', 'Paul Adam', 'Rome',13500),
('5003', 'Lauson Hen', 'San Jose', 12191);

SELECT * FROM EMPLOYEE;

SELECT COUNT(NAME) AS EMPLOYEE_COUNT
FROM EMPLOYEE;

SELECT AVG(SALARY ) AS AVERAGE_SALARY 
FROM EMPLOYEE;

SELECT SUM(SALARY ) AS TOTAL_SALARY 
FROM EMPLOYEE;

SELECT MAX(SALARY ) AS MAXIMUM_SALARY FROM EMPLOYEE;

SELECT MIN(SALARY ) AS MAXIMUM_SALARY  FROM EMPLOYEE;
